import {HandLandmarker,FilesetResolver} from "https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.14";
const WASM="https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.14/wasm";
const MODEL="https://storage.googleapis.com/mediapipe-models/hand_landmarker/hand_landmarker/float16/1/hand_landmarker.task";
const $=id=>document.getElementById(id),canvas=$("canvas"),ctx=canvas.getContext("2d",{alpha:false}),inputVideo=$("inputVideo"),contentVideo=$("contentVideo"),contentImage=$("contentImage");
const KEY="finger-frame-premium-v2-1";
let landmarker=null,inputStream=null,contentStream=null,contentOwned=false,hls=null,inputReady=false,contentKind=null,contentReady=false,raf=0,lastVideoTime=-1,lastTs=performance.now(),fps=0,recorder=null,chunks=[];
let prevRatio=0,prevRatioTs=performance.now(),trail=[];
let portal={state:"IDLE",cx:.5,cy:.5,w:.08,h:.08,angle:0,opacity:0,openP:0,expandP:0,closeP:0,lastSeen:0,openHold:0,closeHold:0};
const settings={mirror:true,fit:"cover",opacity:1,brightness:1.05,contrast:1.12,saturation:1.08,dim:.22,look:"mystic",color:"#f2b84b",glow:34,edge:6,energy:.82,particles:true,trail:true,smoothing:.20,open:1.7,expand:4.6,close:1.3,intent:true};
function status(t){$("topStatus").textContent=t}function out(t){$("outputMsg").textContent=t;$("outputState").textContent=t?"UPDATED":"READY"}function asset(t,ok=false){$("contentAsset").textContent=t;$("contentAsset").style.color=ok?"#a9d7af":"#777"}
async function ensureTracker(){if(landmarker)return;status("LOADING TRACKER");const fs=await FilesetResolver.forVisionTasks(WASM);landmarker=await HandLandmarker.createFromOptions(fs,{baseOptions:{modelAssetPath:MODEL,delegate:"GPU"},runningMode:"VIDEO",numHands:2,minHandDetectionConfidence:.38,minHandPresenceConfidence:.38,minTrackingConfidence:.38});status("TRACKER READY")}
function waitMeta(v){return v.readyState>=1?Promise.resolve():new Promise(r=>v.addEventListener("loadedmetadata",r,{once:true}))}
function stopInput(){if(inputStream){inputStream.getTracks().forEach(t=>t.stop());inputStream=null}inputVideo.pause();inputVideo.srcObject=null;inputVideo.removeAttribute("src");inputVideo.load();inputReady=false}
async function camera(){stopInput();await ensureTracker();try{inputStream=await navigator.mediaDevices.getUserMedia({video:{width:{ideal:1280},height:{ideal:720},frameRate:{ideal:30}},audio:true});inputVideo.srcObject=inputStream;inputVideo.muted=true;await inputVideo.play();await waitMeta(inputVideo);inputReady=true;$("inputState").textContent="LIVE";$("gestureAsset").textContent=`Camera ${inputVideo.videoWidth}×${inputVideo.videoHeight}`;syncCanvas();loop();status("CAMERA LIVE")}catch(e){status("CAMERA BLOCKED");out("Camera permission was not granted")}}
async function gestureFile(f){stopInput();await ensureTracker();inputVideo.src=URL.createObjectURL(f);inputVideo.loop=true;inputVideo.muted=true;await waitMeta(inputVideo);inputReady=true;$("inputState").textContent="VIDEO";$("gestureAsset").textContent=`✓ ${f.name} · ${inputVideo.videoWidth}×${inputVideo.videoHeight}`;syncCanvas();await inputVideo.play().catch(()=>{});loop();status("GESTURE VIDEO READY")}
function syncCanvas(){const w=inputVideo.videoWidth||1280,h=inputVideo.videoHeight||720;if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h}}
function stopContent({detachOnly=false}={}){if(contentStream&&contentOwned&&!detachOnly)contentStream.getTracks().forEach(t=>t.stop());contentStream=null;contentOwned=false;if(hls){hls.destroy();hls=null}contentVideo.pause();contentVideo.srcObject=null;contentVideo.removeAttribute("src");contentVideo.load();contentImage.removeAttribute("src");contentReady=false;contentKind=null}
function videoFileSource(src,label){stopContent();contentKind="video";contentVideo.src=src;contentVideo.loop=true;contentVideo.muted=false;contentVideo.playsInline=true;asset("Loading video…");$("contentState").textContent="LOADING";contentVideo.oncanplay=()=>{contentReady=true;asset(label,true);$("contentState").textContent="VIDEO";contentVideo.play().catch(()=>{})};contentVideo.onerror=()=>{contentReady=false;asset("Video failed to load");$("contentState").textContent="ERROR"}}
function imageFileSource(src,label){stopContent();contentKind="image";asset("Loading image…");$("contentState").textContent="LOADING";contentImage.onload=()=>{contentReady=true;asset(label,true);$("contentState").textContent="IMAGE"};contentImage.onerror=()=>{contentReady=false;asset("Image failed to load");$("contentState").textContent="ERROR"};contentImage.src=src}
function mediaFile(f){if(f.type.startsWith("video/"))videoFileSource(URL.createObjectURL(f),`✓ VIDEO · ${f.name}`);else if(f.type.startsWith("image/"))imageFileSource(URL.createObjectURL(f),`✓ IMAGE · ${f.name}`)}
async function share(){try{stopContent();contentStream=await navigator.mediaDevices.getDisplayMedia({video:true,audio:true});contentOwned=true;contentVideo.srcObject=contentStream;contentKind="video";contentVideo.muted=false;contentVideo.playsInline=true;await contentVideo.play();await waitMeta(contentVideo);contentReady=true;asset("✓ SCREEN SHARE LIVE",true);$("contentState").textContent="SCREEN";contentStream.getVideoTracks()[0]?.addEventListener("ended",()=>stopContent())}catch{out("Screen share cancelled")}}
function loadHls(){const url=$("hlsUrl").value.trim();if(!url)return;stopContent();contentKind="video";asset("Connecting HLS…");$("contentState").textContent="CONNECTING";const ready=()=>{contentReady=true;contentVideo.muted=false;contentVideo.play().catch(()=>{});asset("✓ HLS STREAM LIVE",true);$("contentState").textContent="HLS"};if(contentVideo.canPlayType("application/vnd.apple.mpegurl")){contentVideo.src=url;contentVideo.addEventListener("loadedmetadata",ready,{once:true});contentVideo.addEventListener("error",()=>{contentReady=false;asset("HLS failed");$("contentState").textContent="ERROR"},{once:true})}else if(window.Hls&&window.Hls.isSupported()){hls=new window.Hls({lowLatencyMode:true,enableWorker:true});hls.on(window.Hls.Events.MANIFEST_PARSED,ready);hls.on(window.Hls.Events.ERROR,(_,data)=>{if(!data.fatal)return;if(data.type===window.Hls.ErrorTypes.NETWORK_ERROR){asset("HLS network error · retrying");hls.startLoad()}else if(data.type===window.Hls.ErrorTypes.MEDIA_ERROR){asset("HLS media error · recovering");hls.recoverMediaError()}else{contentReady=false;asset("HLS fatal error");$("contentState").textContent="ERROR";hls.destroy();hls=null}});hls.loadSource(url);hls.attachMedia(contentVideo)}else{asset("HLS unsupported");$("contentState").textContent="ERROR"}}
function setRemoteStream(stream,{owned=false}={}){stopContent({detachOnly:true});contentStream=stream;contentOwned=owned;contentVideo.srcObject=stream;contentKind="video";contentVideo.muted=false;contentVideo.playsInline=true;contentVideo.onloadedmetadata=()=>{contentReady=true;contentVideo.play().catch(()=>{});asset("✓ REMOTE MEDIASTREAM LIVE",true);$("contentState").textContent="REMOTE"};return true}
window.FingerFrameV21={setRemoteStream,clearRemoteStream:()=>{stopContent({detachOnly:!contentOwned});asset("Remote stream detached")}};
function drawInput(){ctx.save();if(settings.mirror){ctx.translate(canvas.width,0);ctx.scale(-1,1)}ctx.drawImage(inputVideo,0,0,canvas.width,canvas.height);ctx.restore()}
function handOpen(h){const wrist=h[0],mcp=h[9];let extended=0;for(const [tip,pip] of [[8,6],[12,10],[16,14],[20,18]]){const dt=Math.hypot(h[tip].x-wrist.x,h[tip].y-wrist.y),dp=Math.hypot(h[pip].x-wrist.x,h[pip].y-wrist.y);if(dt>dp*1.08)extended++}return extended>=3&&Math.hypot(mcp.x-wrist.x,mcp.y-wrist.y)>.035}
function handMetrics(hands,ts){if(!hands||hands.length<2)return null;const hs=hands.slice(0,2),centers=hs.map(h=>({x:h[9].x,y:h[9].y}));if(settings.mirror)centers.forEach(p=>p.x=1-p.x);centers.sort((a,b)=>a.x-b.x);const a=centers[0],b=centers[1],dx=b.x-a.x,dy=b.y-a.y,dist=Math.hypot(dx,dy),palm=hs.reduce((s,h)=>s+Math.hypot(h[5].x-h[17].x,h[5].y-h[17].y),0)/2,ratio=dist/Math.max(.035,palm),cx=(a.x+b.x)/2,cy=(a.y+b.y)/2,angle=Math.atan2(dy,dx),dt=Math.max(16,ts-prevRatioTs),velocity=(ratio-prevRatio)/(dt/1000),intent=hs.every(handOpen);prevRatio=ratio;prevRatioTs=ts;return{cx,cy,angle,ratio,velocity,intent}}
function lerp(a,b,t){return a+(b-a)*t}function lerpAngle(a,b,t){let d=((b-a+Math.PI*3)%(Math.PI*2))-Math.PI;return a+d*t}function ease(t){return 1-Math.pow(1-Math.max(0,Math.min(1,t)),3)}
function updatePortal(d,dt,ts){if(!d){if(ts-portal.lastSeen>420&&portal.state!=="IDLE"&&portal.state!=="CLOSING")portal.state="CLOSING";animatePortal(dt);return}portal.lastSeen=ts;const allowed=!settings.intent||d.intent;
 if(portal.state==="IDLE"){if(allowed&&d.ratio>settings.open&&d.velocity>-.15){portal.openHold+=dt;if(portal.openHold>180){portal.state="OPENING";portal.cx=d.cx;portal.cy=d.cy;portal.openP=0;portal.opacity=0}}else portal.openHold=0}
 if(["OPENING","ACTIVE","EXPANDING","IMMERSIVE"].includes(portal.state)){portal.cx=lerp(portal.cx,d.cx,settings.smoothing);portal.cy=lerp(portal.cy,d.cy,settings.smoothing);portal.angle=lerpAngle(portal.angle,d.angle,settings.smoothing);const targetW=Math.max(.15,Math.min(.86,(d.ratio/settings.expand)*.72));portal.w=lerp(portal.w,targetW,settings.smoothing);portal.h=lerp(portal.h,targetW*.58,settings.smoothing);if(allowed&&d.ratio>settings.expand&&portal.state!=="IMMERSIVE")portal.state="EXPANDING";if(portal.state==="IMMERSIVE"&&d.ratio<settings.expand*.78)portal.state="ACTIVE";if(d.ratio<settings.close){portal.closeHold+=dt;if(portal.closeHold>240)portal.state="CLOSING"}else portal.closeHold=0}
 animatePortal(dt);$("portalState").textContent=portal.state;$("portalDebug").textContent=`${portal.state} · ${d?d.ratio.toFixed(2)+'×':'NO HANDS'}`;$("gesturePill").textContent=portal.state==="IDLE"?"OPEN BOTH HANDS & SEPARATE":portal.state;$("gesturePill").classList.toggle("active",portal.state!=="IDLE")}
function animatePortal(dt){const k=dt/16.67;if(portal.state==="OPENING"){portal.openP=Math.min(1,portal.openP+.045*k);portal.opacity=ease(portal.openP);if(portal.openP>=1)portal.state="ACTIVE"}else if(portal.state==="EXPANDING"){portal.expandP=Math.min(1,portal.expandP+.035*k);if(portal.expandP>=1)portal.state="IMMERSIVE"}else if(portal.state==="ACTIVE"){portal.expandP=Math.max(0,portal.expandP-.045*k);portal.opacity=Math.min(1,portal.opacity+.05*k)}else if(portal.state==="IMMERSIVE"){portal.expandP=Math.min(1,portal.expandP+.03*k);portal.opacity=1}else if(portal.state==="CLOSING"){portal.closeP=Math.min(1,portal.closeP+.055*k);portal.opacity=1-ease(portal.closeP);if(portal.closeP>=1)resetPortal()}}
function resetPortal(){portal={state:"IDLE",cx:.5,cy:.5,w:.08,h:.08,angle:0,opacity:0,openP:0,expandP:0,closeP:0,lastSeen:0,openHold:0,closeHold:0};trail=[]}
function sourceDims(){if(contentKind==="image")return{w:contentImage.naturalWidth||1,h:contentImage.naturalHeight||1};return{w:contentVideo.videoWidth||1,h:contentVideo.videoHeight||1}}
function drawLocalFitted(src,w,h){const d=sourceDims();let dx=-w/2,dy=-h/2,dw=w,dh=h;if(settings.fit!=="stretch"){const k=settings.fit==="contain"?Math.min(w/d.w,h/d.h):Math.max(w/d.w,h/d.h);dw=d.w*k;dh=d.h*k;dx=-dw/2;dy=-dh/2}ctx.drawImage(src,dx,dy,dw,dh)}
function portalGeometry(){const e=ease(portal.expandP),openScale=.12+.88*ease(portal.openP||1),cx=lerp(portal.cx*canvas.width,canvas.width/2,e),cy=lerp(portal.cy*canvas.height,canvas.height/2,e),w=lerp(portal.w*canvas.width,canvas.width*1.12,e)*openScale,h=lerp(portal.h*canvas.height,canvas.height*1.12,e)*openScale,angle=lerp(portal.angle,0,e);return{cx,cy,w,h,angle}}
function shapePath(w,h){ctx.beginPath();if(settings.look==="clean"){const r=Math.min(38,h*.12);ctx.moveTo(-w/2+r,-h/2);ctx.arcTo(w/2,-h/2,w/2,h/2,r);ctx.arcTo(w/2,h/2,-w/2,h/2,r);ctx.arcTo(-w/2,h/2,-w/2,-h/2,r);ctx.arcTo(-w/2,-h/2,w/2,-h/2,r);ctx.closePath()}else ctx.ellipse(0,0,w/2,h/2,0,0,Math.PI*2)}
function drawPortal(){if(portal.opacity<=.01)return;const g=portalGeometry();if(settings.trail&&portal.state!=="IMMERSIVE"){trail.unshift({...g,a:portal.opacity});trail=trail.slice(0,3);trail.slice(1).forEach((q,i)=>drawEdge(q,.11/(i+1),true))}
 if(settings.dim>0){ctx.save();ctx.fillStyle=`rgba(0,0,0,${settings.dim*portal.opacity*(1-portal.expandP*.65)})`;ctx.fillRect(0,0,canvas.width,canvas.height);ctx.restore()}
 ctx.save();ctx.translate(g.cx,g.cy);ctx.rotate(g.angle);shapePath(g.w,g.h);ctx.clip();ctx.globalAlpha=settings.opacity;ctx.filter=`brightness(${settings.brightness}) contrast(${settings.contrast}) saturate(${settings.saturation})`;if(contentReady){const src=contentKind==="image"?contentImage:contentVideo;try{drawLocalFitted(src,g.w,g.h)}catch{}}ctx.filter="none";ctx.globalAlpha=.18*(1-portal.expandP);const vignette=ctx.createRadialGradient(0,0,Math.min(g.w,g.h)*.15,0,0,Math.max(g.w,g.h)*.62);vignette.addColorStop(0,"rgba(0,0,0,0)");vignette.addColorStop(1,"rgba(0,0,0,.78)");ctx.fillStyle=vignette;ctx.fillRect(-g.w/2,-g.h/2,g.w,g.h);ctx.restore();drawEdge(g,portal.opacity,false)}
function drawEdge(g,a=1,ghost=false){ctx.save();ctx.translate(g.cx,g.cy);ctx.rotate(g.angle);ctx.globalAlpha=a;ctx.strokeStyle=settings.color;ctx.lineWidth=ghost?Math.max(1,settings.edge*.45):settings.edge;ctx.shadowColor=settings.color;ctx.shadowBlur=settings.glow*(ghost?.5:(.5+.7*settings.energy));shapePath(g.w,g.h);ctx.stroke();if(!ghost&&settings.look==="mystic"){const t=performance.now()*.001;for(let i=0;i<3;i++){ctx.globalAlpha=a*(.22+i*.12);ctx.lineWidth=Math.max(1,settings.edge*.28);ctx.beginPath();const off=4+i*5,phase=t*(.35+i*.08)+i*1.7;ctx.ellipse(0,0,g.w/2+off,g.h/2+off*.7,0,phase,phase+Math.PI*(1.25+.18*Math.sin(t+i)));ctx.stroke()}if(settings.particles)particles(g.w,g.h,a)}ctx.restore()}
function particles(w,h,a){const n=Math.round(20+settings.energy*42),t=performance.now()*.001;ctx.fillStyle=settings.color;for(let i=0;i<n;i++){const seed=i*12.9898,ang=(i/n)*Math.PI*2+t*(i%2?.22:-.16)+Math.sin(seed)*.2,rx=w/2+8+Math.sin(t*1.8+seed)*9,ry=h/2+6+Math.cos(t*1.4+seed*.7)*7;ctx.globalAlpha=a*(.16+.62*((i%9)/9));ctx.beginPath();ctx.arc(Math.cos(ang)*rx,Math.sin(ang)*ry,1+(i%4)*.45,0,Math.PI*2);ctx.fill()}}
function render(ts){raf=requestAnimationFrame(render);if(!inputReady||inputVideo.readyState<2)return;syncCanvas();drawInput();const dt=Math.min(50,Math.max(1,ts-lastTs));lastTs=ts;if(landmarker&&inputVideo.currentTime!==lastVideoTime){lastVideoTime=inputVideo.currentTime;try{const r=landmarker.detectForVideo(inputVideo,performance.now());updatePortal(handMetrics(r.landmarks,ts),dt,ts)}catch{}}else if(portal.state!=="IDLE")animatePortal(dt);drawPortal();const f=1000/dt;fps=fps?fps*.9+f*.1:f;$("metrics").textContent=`${fps.toFixed(0)} FPS · ${contentReady?"content live":"no content"}`}
function loop(){if(!raf)raf=requestAnimationFrame(render)}
function labels(){$("opacityValue").textContent=(+settings.opacity).toFixed(2);$("brightnessValue").textContent=(+settings.brightness).toFixed(2);$("contrastValue").textContent=(+settings.contrast).toFixed(2);$("saturationValue").textContent=(+settings.saturation).toFixed(2);$("dimValue").textContent=(+settings.dim).toFixed(2);$("glowValue").textContent=settings.glow+"px";$("edgeValue").textContent=settings.edge+"px";$("energyValue").textContent=(+settings.energy).toFixed(2);$("smoothValue").textContent=(+settings.smoothing).toFixed(2);$("openValue").textContent=settings.open.toFixed(2)+"×";$("expandValue").textContent=settings.expand.toFixed(2)+"×";$("closeValue").textContent=settings.close.toFixed(2)+"×";$("lookState").textContent=settings.look.toUpperCase()}
function syncUI(){for(const [id,key] of [["mirrorInput","mirror"],["particlesOn","particles"],["trailOn","trail"],["intentGate","intent"]])$(id).checked=!!settings[key];for(const [id,key] of [["contentFit","fit"],["contentOpacity","opacity"],["brightness","brightness"],["contrast","contrast"],["saturation","saturation"],["backdropDim","dim"],["portalColor","color"],["portalGlow","glow"],["portalEdge","edge"],["portalEnergy","energy"],["smoothing","smoothing"],["openThreshold","open"],["expandThreshold","expand"],["closeThreshold","close"]])$(id).value=settings[key];document.querySelectorAll('[data-look]').forEach(b=>b.classList.toggle('active',b.dataset.look===settings.look));labels()}
function save(){localStorage.setItem(KEY,JSON.stringify(settings));out("✓ Settings saved")}function restore(){try{Object.assign(settings,JSON.parse(localStorage.getItem(KEY)||"{}"));syncUI();out("✓ Settings restored")}catch{}}
function audioTracksForRecord(){const tracks=[];if($("micAudio").checked&&inputStream)tracks.push(...inputStream.getAudioTracks());if($("contentAudio").checked){if(contentStream)tracks.push(...contentStream.getAudioTracks());else if(contentKind==="video"&&typeof contentVideo.captureStream==="function"){try{tracks.push(...contentVideo.captureStream().getAudioTracks())}catch{}}}return tracks}
function record(){if(recorder&&recorder.state==="recording")return;try{const rfps=+$('recordFps').value,vs=canvas.captureStream(rfps),stream=new MediaStream([...vs.getVideoTracks(),...audioTracksForRecord()]),mime=MediaRecorder.isTypeSupported("video/webm;codecs=vp9")?"video/webm;codecs=vp9":"video/webm";chunks=[];recorder=new MediaRecorder(stream,{mimeType:mime,videoBitsPerSecond:14_000_000});recorder.ondataavailable=e=>e.data.size&&chunks.push(e.data);recorder.onstop=()=>{const b=new Blob(chunks,{type:mime});download(b,`portal-studio-v21-${Date.now()}.webm`);$("recordingBadge").classList.remove("on");out(`✓ Video downloaded · ${(b.size/1048576).toFixed(1)} MB`)};recorder.start(250);$("recordingBadge").classList.add("on");out(`● Recording ${rfps} FPS`)}catch(e){out("Recording unavailable in this browser")}}
function download(blob,name){const a=document.createElement("a"),u=URL.createObjectURL(blob);a.href=u;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),2500)}
function wire(){$("startCamera").onclick=camera;$("gestureFile").onchange=e=>e.target.files[0]&&gestureFile(e.target.files[0]);$("mirrorInput").onchange=e=>settings.mirror=e.target.checked;document.querySelectorAll('[data-content]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-content]').forEach(x=>x.classList.toggle('active',x===b));const m=b.dataset.content;$("shareScreen").classList.toggle("hidden",m!=="screen");$("hlsBox").classList.toggle("hidden",m!=="hls");$("webrtcBox").classList.toggle("hidden",m!=="webrtc")});$("contentFile").onchange=e=>e.target.files[0]&&mediaFile(e.target.files[0]);$("shareScreen").onclick=share;$("loadHls").onclick=loadHls;$("clearRemote").onclick=()=>window.FingerFrameV21.clearRemoteStream();for(const [id,key] of [["contentFit","fit"],["contentOpacity","opacity"],["brightness","brightness"],["contrast","contrast"],["saturation","saturation"],["backdropDim","dim"],["portalGlow","glow"],["portalEdge","edge"],["portalEnergy","energy"],["smoothing","smoothing"],["openThreshold","open"],["expandThreshold","expand"],["closeThreshold","close"]])$(id).oninput=e=>{settings[key]=id==="contentFit"?e.target.value:+e.target.value;labels()};$("portalColor").oninput=e=>settings.color=e.target.value;$("particlesOn").onchange=e=>settings.particles=e.target.checked;$("trailOn").onchange=e=>settings.trail=e.target.checked;$("intentGate").onchange=e=>settings.intent=e.target.checked;document.querySelectorAll('[data-look]').forEach(b=>b.onclick=()=>{settings.look=b.dataset.look;document.querySelectorAll('[data-look]').forEach(x=>x.classList.toggle('active',x===b));labels()});$("forceReset").onclick=resetPortal;$("previewClean").onclick=()=>document.body.classList.add("preview");$("exitPreview").onclick=()=>document.body.classList.remove("preview");document.addEventListener("keydown",e=>{if(e.key==="Escape")document.body.classList.remove("preview")});$("recordVideo").onclick=record;$("stopRecord").onclick=()=>recorder&&recorder.state==="recording"&&recorder.stop();$("downloadPng").onclick=()=>canvas.toBlob(b=>b&&download(b,`portal-studio-v21-${Date.now()}.png`));$("saveSettings").onclick=save;$("restoreSettings").onclick=restore}
wire();syncUI();status("V2.1 READY · POLISHED PORTAL");