const DECART_SDK_URL="https://esm.sh/@decartai/sdk@0.1.17";
const $=id=>document.getElementById(id);
const inputVideo=$("inputVideo"),lucyVideo=$("lucyVideo"),bridge=$("aiBridge"),bctx=bridge.getContext("2d",{alpha:false});
const EFFECTS={movie3d:"Change the style of the video to a 3D animated movie: stylized CGI animation, expressive character design, soft cinematic lighting.",anime:"Change the style of the video to hand-drawn anime: clean black line art, flat cel shading, vibrant colors, expressive eyes.",cyberpunk:"Change the style of the video to neon cyberpunk: glowing cyan and magenta lighting, reflective surfaces, futuristic atmosphere.",watercolor:"Change the style of the video to a watercolor painting: soft loose brushstrokes, gentle color bleeds, paper texture, muted pastel palette.",lego:"Change the style of the video to a glossy plastic brick-built stop-motion world with a toy-like character and visible studs."};
let realtimeClient=null,lucyStream=null,bridgeStream=null,bridgeRaf=0,sourceMode="original",connecting=false,reconnectTimer=null,reconnectAttempt=0,userDisconnected=false;
function aiState(state,text){const e=$("aiState");e.textContent=text;e.className=`ai-state ${state}`;$("aiSessionState").textContent=text;$("diagSession").textContent=text}
function msg(t){$("aiMessage").textContent=t}
function cameraStream(){return inputVideo?.srcObject instanceof MediaStream?inputVideo.srcObject:null}
function cameraReady(){const s=cameraStream(),ok=!!(s&&s.getVideoTracks().some(t=>t.readyState==="live")&&inputVideo.readyState>=2);$("aiCameraState").textContent=ok?"READY":"WAITING";return ok}
function keyValue(){return $("decartKey").value.trim()}
function setAuth(){const ok=!!keyValue();$("aiAuthState").textContent=ok?"KEY READY":"NO KEY";$("diagAuth").textContent=ok?"KEY READY":"NO KEY";return ok}
function saveKey(){const k=keyValue();localStorage.removeItem("portal-v31-decart-key");sessionStorage.removeItem("portal-v31-decart-key");if(k)($("rememberDecartKey").checked?localStorage:sessionStorage).setItem("portal-v31-decart-key",k);setAuth();return k}
function restore(){const k=localStorage.getItem("portal-v31-decart-key")||sessionStorage.getItem("portal-v31-decart-key")||"";$("decartKey").value=k;$("rememberDecartKey").checked=!!localStorage.getItem("portal-v31-decart-key");const style=localStorage.getItem("portal-v31-style")||"movie3d";$("aiStyle").value=style;$("customPrompt").value=localStorage.getItem("portal-v31-custom")||"";$("customPromptBox").classList.toggle("hidden",style!=="custom");setAuth()}
function prompt(){const s=$("aiStyle").value;if(s==="custom")return $("customPrompt").value.trim()||"Change the style of the video to a cinematic surreal alternate world.";return EFFECTS[s]||EFFECTS.movie3d}
function enableAiModes(on){document.querySelector('[data-ai-source="ai"]').disabled=!on;document.querySelector('[data-ai-source="split"]').disabled=!on;if(!on&&sourceMode!=="original")setSource("original")}
function ensureBridge(){if(!cameraReady())throw new Error("Start the camera first.");const w=inputVideo.videoWidth||1280,h=inputVideo.videoHeight||720;if(bridge.width!==w||bridge.height!==h){bridge.width=w;bridge.height=h}if(!bridgeStream){bridgeStream=bridge.captureStream(30);window.FingerFrameV211?.setRemoteStream(bridgeStream,{owned:false})}if(!bridgeRaf)bridgeRaf=requestAnimationFrame(drawBridge)}
function drawCover(v,x,y,w,h){if(!v||v.readyState<2)return false;const sw=v.videoWidth||w,sh=v.videoHeight||h,k=Math.max(w/sw,h/sh),dw=sw*k,dh=sh*k,dx=x+(w-dw)/2,dy=y+(h-dh)/2;bctx.save();bctx.beginPath();bctx.rect(x,y,w,h);bctx.clip();bctx.translate(dx+dw,dy);bctx.scale(-1,1);bctx.drawImage(v,0,0,dw,dh);bctx.restore();return true}
function drawBridge(){bridgeRaf=requestAnimationFrame(drawBridge);if(!cameraReady())return;const w=bridge.width,h=bridge.height;bctx.fillStyle="#000";bctx.fillRect(0,0,w,h);if(sourceMode==="original")drawCover(inputVideo,0,0,w,h);else if(sourceMode==="ai"){if(!drawCover(lucyVideo,0,0,w,h))drawCover(inputVideo,0,0,w,h)}else{drawCover(inputVideo,0,0,w/2,h);if(!drawCover(lucyVideo,w/2,0,w/2,h))drawCover(inputVideo,w/2,0,w/2,h);bctx.fillStyle="rgba(255,255,255,.75)";bctx.fillRect(w/2-1,0,2,h)}}
function setSource(mode){if((mode==="ai"||mode==="split")&&!lucyStream){msg("Connect Lucy before selecting AI or Split.");return}sourceMode=mode;document.querySelectorAll("[data-ai-source]").forEach(b=>b.classList.toggle("active",b.dataset.aiSource===mode));$("diagAiOutput").textContent=mode.toUpperCase();try{ensureBridge();document.querySelector('[data-tab="portal"]')?.click();document.querySelector('[data-content="webrtc"]')?.click()}catch(e){msg(e.message)} }
async function pushPrompt(){if(!realtimeClient||!lucyStream){msg("Lucy is not live yet.");return}localStorage.setItem("portal-v31-style",$("aiStyle").value);localStorage.setItem("portal-v31-custom",$("customPrompt").value);try{try{await realtimeClient.set({prompt:prompt(),enhance:true})}catch{await realtimeClient.set({prompt:{text:prompt()},enhance:true})}msg("Live style updated.")}catch(e){msg(`Style update failed: ${(e?.message||e).toString().slice(0,100)}`)}}
async function disconnectClient(){try{await realtimeClient?.disconnect?.()}catch{}try{realtimeClient?.close?.()}catch{}realtimeClient=null;lucyStream=null;lucyVideo.pause();lucyVideo.srcObject=null;$("diagRemote").textContent="NO STREAM";enableAiModes(false)}
function retry(reason){if(userDisconnected||reconnectTimer)return;reconnectAttempt++;const ms=Math.min(30000,2000*Math.pow(1.7,reconnectAttempt-1));aiState("connecting",`RETRY ${Math.ceil(ms/1000)}s`);msg(`${reason} Retrying…`);reconnectTimer=setTimeout(()=>{reconnectTimer=null;connectLucy(true)},ms)}
async function connectLucy(isRetry=false){if(connecting)return;if(!cameraReady()){aiState("error","CAMERA FIRST");msg("Start the camera in the PORTAL tab first.");return}const apiKey=saveKey();if(!apiKey){aiState("error","KEY REQUIRED");msg("Add a Decart API key or development client token first.");return}connecting=true;userDisconnected=false;aiState("connecting",isRetry?"RECONNECTING":"CONNECTING");$("diagSdk").textContent="LOADING";msg("Opening Lucy 2.5 realtime session…");try{await disconnectClient();const {createDecartClient,models}=await import(DECART_SDK_URL);$("diagSdk").textContent="READY";const client=createDecartClient({apiKey});const model=models.realtime("lucy-2.5");const videoOnly=new MediaStream(cameraStream().getVideoTracks());realtimeClient=await client.realtime.connect(videoOnly,{model,initialState:{prompt:{text:prompt(),enhance:true}},onRemoteStream:async stream=>{lucyStream=stream;lucyVideo.srcObject=stream;lucyVideo.muted=true;await lucyVideo.play().catch(()=>{});reconnectAttempt=0;aiState("live","LIVE");$("diagRemote").textContent=`${stream.getVideoTracks().length} VIDEO TRACK`;enableAiModes(true);msg("Lucy is live. AI and Split are now available.");stream.getVideoTracks().forEach(t=>t.addEventListener("ended",()=>retry("Remote video ended."),{once:true}));ensureBridge()},onError:e=>retry((e?.message||"Lucy error").toString().slice(0,90)),onDisconnect:r=>retry(`Lucy disconnected${r?`: ${r}`:"."}`)});$("diagAuth").textContent="OK"}catch(e){console.error(e);aiState("error","AI OFFLINE");$("diagRemote").textContent="NO STREAM";retry((e?.message||"Connection failed").toString().slice(0,90))}finally{connecting=false}}
async function disconnectLucy(){userDisconnected=true;if(reconnectTimer)clearTimeout(reconnectTimer);reconnectTimer=null;reconnectAttempt=0;await disconnectClient();aiState("off","OFFLINE");setSource("original");msg("Lucy disconnected. Original portal mode remains available.")}
function tabs(){document.querySelectorAll("[data-tab]").forEach(b=>b.onclick=()=>{document.querySelectorAll("[data-tab]").forEach(x=>x.classList.toggle("active",x===b));document.querySelectorAll("[data-page]").forEach(p=>p.classList.toggle("active",p.dataset.page===b.dataset.tab));if(b.dataset.tab==="ai")cameraReady()})}
function wire(){restore();tabs();$("decartKey").oninput=setAuth;$("connectLucy").onclick=()=>connectLucy(false);$("disconnectLucy").onclick=disconnectLucy;$("updateAiStyle").onclick=pushPrompt;$("aiStyle").onchange=()=>{$("customPromptBox").classList.toggle("hidden",$("aiStyle").value!=="custom");localStorage.setItem("portal-v31-style",$("aiStyle").value);if(lucyStream)pushPrompt()};$("customPrompt").onchange=()=>localStorage.setItem("portal-v31-custom",$("customPrompt").value);document.querySelectorAll("[data-ai-source]").forEach(b=>b.onclick=()=>setSource(b.dataset.aiSource));$("startCamera").addEventListener("click",()=>setTimeout(()=>{cameraReady();if(cameraReady()){$("aiCameraState").textContent="READY"}},700));window.addEventListener("beforeunload",()=>{userDisconnected=true;realtimeClient?.disconnect?.()});setInterval(cameraReady,1000)}
window.PortalStudioV31={connectLucy,disconnectLucy,setSource,pushPrompt,getState:()=>({sourceMode,lucyLive:!!lucyStream,cameraLive:cameraReady()})};wire();aiState("off","OFFLINE");enableAiModes(false);