import {HandLandmarker,FilesetResolver} from "https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.14";
const WASM="https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.14/wasm";
const MODEL="https://storage.googleapis.com/mediapipe-models/hand_landmarker/hand_landmarker/float16/1/hand_landmarker.task";
const $=id=>document.getElementById(id);
const canvas=$("canvas"),ctx=canvas.getContext("2d",{alpha:false}),inputVideo=$("inputVideo"),contentVideo=$("contentVideo"),contentImage=$("contentImage");
const KEY="finger-frame-premium-v2-1-1";
let landmarker=null,inputStream=null,contentStream=null,contentOwned=false,hls=null,inputReady=false,contentKind=null,contentReady=false,raf=0,lastVideoTime=-1,lastTs=performance.now(),fps=0,recorder=null,chunks=[];
let smoothPalm=0,smoothRatio=0,prevRatio=0,prevRatioTs=performance.now(),badOpenFrames=0,trail=[],manualPortal=false;
let portal={state:"IDLE",cx:.5,cy:.5,w:.08,h:.08,angle:0,opacity:0,openP:0,expandP:0,closeP:0,lastSeen:0,openHold:0,closeHold:0};
const settings={mirror:true,fit:"cover",opacity:1,brightness:1.05,contrast:1.12,saturation:1.08,dim:.22,look:"mystic",color:"#f2b84b",glow:34,edge:6,energy:.82,particles:true,trail:true,smoothing:.20,open:1.55,expand:4.4,close:1.2,intent:false};
function status(t){$("topStatus").textContent=t}function out(t){$("outputMsg").textContent=t;$("outputState").textContent=t?"UPDATED":"READY"}function asset(t,ok=false){$("contentAsset").textContent=t;$("contentAsset").style.color=ok?"#a9d7af":"#777"}
async function ensureTracker(){if(landmarker)return;status("LOADING TRACKER");const fs=await FilesetResolver.forVisionTasks(WASM);landmarker=await HandLandmarker.createFromOptions(fs,{baseOptions:{modelAssetPath:MODEL,delegate:"GPU"},runningMode:"VIDEO",numHands:2,minHandDetectionConfidence:.30,minHandPresenceConfidence:.30,minTrackingConfidence:.32});status("TRACKER READY")}
function waitMeta(v){return v.readyState>=1?Promise.resolve():new Promise(r=>v.addEventListener("loadedmetadata",r,{once:true}))}
function stopInput(){if(inputStream){inputStream.getTracks().forEach(t=>t.stop());inputStream=null}inputVideo.pause();inputVideo.srcObject=null;inputVideo.removeAttribute("src");inputVideo.load();inputReady=false;lastVideoTime=-1}
async function camera(){stopInput();await ensureTracker();try{inputStream=await navigator.mediaDevices.getUserMedia({video:{width:{ideal:1280},height:{ideal:720},frameRate:{ideal:30}},audio:true});inputVideo.srcObject=inputStream;inputVideo.muted=true;inputVideo.playsInline=true;await inputVideo.play();await waitMeta(inputVideo);inputReady=true;$("inputState").textContent="LIVE";$("gestureAsset").textContent=`Camera ${inputVideo.videoWidth}×${inputVideo.videoHeight}`;syncCanvas();loop();status("CAMERA LIVE")}catch(e){status("CAMERA BLOCKED");out("Camera permission was not granted")}}
async function gestureFile(f){stopInput();await ensureTracker();inputVideo.src=URL.createObjectURL(f);inputVideo.loop=true;inputVideo.muted=true;inputVideo.playsInline=true;await waitMeta(inputVideo);inputReady=true;$("inputState").textContent="VIDEO";$("gestureAsset").textContent=`✓ ${f.name} · ${inputVideo.videoWidth}×${inputVideo.videoHeight}`;syncCanvas();await inputVideo.play().catch(e=>out(`Gesture video play blocked: ${e.message}`));loop();status("GESTURE VIDEO READY")}
function syncCanvas(){const w=inputVideo.videoWidth||1280,h=inputVideo.videoHeight||720;if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h}}
function stopContent({detachOnly=false}={}){if(contentStream&&contentOwned&&!detachOnly)contentStream.getTracks().forEach(t=>t.stop());contentStream=null;contentOwned=false;if(hls){hls.destroy();hls=null}contentVideo.pause();contentVideo.srcObject=null;contentVideo.removeAttribute("src");contentVideo.load();contentImage.removeAttribute("src");contentVideo.classList.remove("active");contentImage.classList.remove("active");contentReady=false;contentKind=null;diag()}
function videoFileSource(src,label){stopContent();contentKind="video";contentVideo.src=src;contentVideo.loop=true;contentVideo.muted=true;contentVideo.playsInline=true;contentVideo.classList.add("active");asset("Loading video…");$("contentState").textContent="LOADING";contentVideo.oncanplay=async()=>{contentReady=true;asset(label,true);$("contentState").textContent="VIDEO";diag();try{await contentVideo.play();status("CONTENT VIDEO PLAYING")}catch(e){out(`Video ready · press play in preview (${e.message})`)}};contentVideo.onerror=()=>{contentReady=false;asset("Video failed to load");$("contentState").textContent="ERROR";diag()}}
function imageFileSource(src,label){stopContent();contentKind="image";contentImage.classList.add("active");asset("Loading image…");$("contentState").textContent="LOADING";contentImage.onload=()=>{contentReady=true;asset(label,true);$("contentState").textContent="IMAGE";diag()};contentImage.onerror=()=>{contentReady=false;asset("Image failed to load");$("contentState").textContent="ERROR";diag()};contentImage.src=src}
function mediaFile(f){if(f.type.startsWith("video/"))videoFileSource(URL.createObjectURL(f),`✓ VIDEO · ${f.name}`);else if(f.type.startsWith("image/"))imageFileSource(URL.createObjectURL(f),`✓ IMAGE · ${f.name}`)}
async function share(){try{stopContent();contentStream=await navigator.mediaDevices.getDisplayMedia({video:true,audio:true});contentOwned=true;contentVideo.srcObject=contentStream;contentVideo.muted=true;contentVideo.playsInline=true;contentVideo.classList.add("active");contentKind="video";await contentVideo.play();await waitMeta(contentVideo);contentReady=true;asset("✓ SCREEN SHARE LIVE",true);$("contentState").textContent="SCREEN";diag();contentStream.getVideoTracks()[0]?.addEventListener("ended",()=>stopContent())}catch{out("Screen share cancelled")}}
function loadHls(){const url=$("hlsUrl").value.trim();if(!url)return;stopContent();contentKind="video";contentVideo.classList.add("active");contentVideo.muted=true;contentVideo.playsInline=true;asset("Connecting HLS…");$("contentState").textContent="CONNECTING";const ready=async()=>{contentReady=true;asset("✓ HLS STREAM LIVE",true);$("contentState").textContent="HLS";diag();try{await contentVideo.play()}catch(e){out(`HLS ready · playback blocked: ${e.message}`)}};if(contentVideo.canPlayType("application/vnd.apple.mpegurl")){contentVideo.src=url;contentVideo.addEventListener("loadedmetadata",ready,{once:true});contentVideo.addEventListener("error",()=>{contentReady=false;asset("HLS failed");$("contentState").textContent="ERROR";diag()},{once:true})}else if(window.Hls&&window.Hls.isSupported()){hls=new window.Hls({lowLatencyMode:true,enableWorker:true});hls.on(window.Hls.Events.MANIFEST_PARSED,ready);hls.on(window.Hls.Events.ERROR,(_,data)=>{if(!data.fatal)return;if(data.type===window.Hls.ErrorTypes.NETWORK_ERROR){asset("HLS network error · retrying");hls.startLoad()}else if(data.type===window.Hls.ErrorTypes.MEDIA_ERROR){asset("HLS media error · recovering");hls.recoverMediaError()}else{contentReady=false;asset("HLS fatal error");$("contentState").textContent="ERROR";hls.destroy();hls=null;diag()}});hls.loadSource(url);hls.attachMedia(contentVideo)}else{asset("HLS unsupported");$("contentState").textContent="ERROR";diag()}}
function setRemoteStream(stream,{owned=false}={}){stopContent({detachOnly:true});contentStream=stream;contentOwned=owned;contentVideo.srcObject=stream;contentVideo.muted=true;contentVideo.playsInline=true;contentVideo.classList.add("active");contentKind="video";contentVideo.onloadedmetadata=async()=>{contentReady=true;asset("✓ REMOTE MEDIASTREAM LIVE",true);$("contentState").textContent="REMOTE";diag();try{await contentVideo.play()}catch(e){out(`Remote stream ready · playback blocked: ${e.message}`)}};return true}
window.FingerFrameV211={setRemoteStream,clearRemoteStream:()=>{stopContent({detachOnly:!contentOwned});asset("Remote stream detached")}};
function drawInput(){ctx.save();if(settings.mirror){ctx.translate(canvas.width,0);ctx.scale(-1,1)}ctx.drawImage(inputVideo,0,0,canvas.width,canvas.height);ctx.restore()}
function fingerScore(h){const wrist=h[0];let extended=0;for(const [tip,pip] of [[8,6],[12,10],[16,14],[20,18]]){const dt=Math.hypot(h[tip].x-wrist.x,h[tip].y-wrist.y),dp=Math.hypot(h[pip].x-wrist.x,h[pip].y-wrist.y);if(dt>dp*1.02)extended++}return extended/4}
function handMetrics(hands,ts){const count=hands?.length||0;if(count<2){diag({hands:count});return null}const hs=hands.slice(0,2),centers=hs.map(h=>({x:h[9].x,y:h[9].y}));if(settings.mirror)centers.forEach(p=>p.x=1-p.x);centers.sort((a,b)=>a.x-b.x);const a=centers[0],b=centers[1],dx=b.x-a.x,dy=b.y-a.y,dist=Math.hypot(dx,dy),rawPalm=hs.reduce((s,h)=>s+Math.hypot(h[5].x-h[17].x,h[5].y-h[17].y),0)/2;smoothPalm=smoothPalm?lerp(smoothPalm,rawPalm,.18):rawPalm;const rawRatio=dist/Math.max(.04,smoothPalm);smoothRatio=smoothRatio?lerp(smoothRatio,rawRatio,.24):rawRatio;const dt=Math.max(16,ts-prevRatioTs),velocity=(smoothRatio-prevRatio)/(dt/1000);prevRatio=smoothRatio;prevRatioTs=ts;const intent=(fingerScore(hs[0])+fingerScore(hs[1]))/2,cx=(a.x+b.x)/2,cy=(a.y+b.y)/2,angle=Math.atan2(dy,dx);const d={hands:2,cx,cy,angle,ratio:smoothRatio,velocity,intent};diag(d);return d}
function lerp(a,b,t){return a+(b-a)*t}function lerpAngle(a,b,t){let d=((b-a+Math.PI*3)%(Math.PI*2))-Math.PI;return a+d*t}function ease(t){return 1-Math.pow(1-Math.max(0,Math.min(1,t)),3)}
function updatePortal(d,dt,ts){if(manualPortal){animatePortal(dt);return}if(!d){if(ts-portal.lastSeen>500&&portal.state!=="IDLE"&&portal.state!=="CLOSING")portal.state="CLOSING";animatePortal(dt);return}portal.lastSeen=ts;const intentOK=!settings.intent||d.intent>=.50;
 if(portal.state==="IDLE"){const qualifies=intentOK&&d.ratio>settings.open;if(qualifies){portal.openHold+=dt;badOpenFrames=0}else{badOpenFrames++;portal.openHold=Math.max(0,portal.openHold-(badOpenFrames<=4?dt*.18:dt*.65))}if(portal.openHold>140){portal.state="OPENING";portal.cx=d.cx;portal.cy=d.cy;portal.openP=0;portal.opacity=0;portal.closeP=0}}
 if(["OPENING","ACTIVE","EXPANDING","IMMERSIVE"].includes(portal.state)){portal.cx=lerp(portal.cx,d.cx,settings.smoothing);portal.cy=lerp(portal.cy,d.cy,settings.smoothing);portal.angle=lerpAngle(portal.angle,d.angle,settings.smoothing);const targetW=Math.max(.16,Math.min(.88,(d.ratio/settings.expand)*.74));portal.w=lerp(portal.w,targetW,settings.smoothing);portal.h=lerp(portal.h,targetW*.58,settings.smoothing);if(d.ratio>settings.expand&&portal.state!=="IMMERSIVE")portal.state="EXPANDING";if(portal.state==="IMMERSIVE"&&d.ratio<settings.expand*.78)portal.state="ACTIVE";if(d.ratio<settings.close){portal.closeHold+=dt;if(portal.closeHold>240)portal.state="CLOSING"}else portal.closeHold=Math.max(0,portal.closeHold-dt*.5)}
 animatePortal(dt);updatePortalUI()}
function animatePortal(dt){const k=dt/16.67;if(portal.state==="OPENING"){portal.openP=Math.min(1,portal.openP+.055*k);portal.opacity=ease(portal.openP);if(portal.openP>=1)portal.state="ACTIVE"}else if(portal.state==="EXPANDING"){portal.expandP=Math.min(1,portal.expandP+.038*k);portal.opacity=1;if(portal.expandP>=1)portal.state="IMMERSIVE"}else if(portal.state==="ACTIVE"){portal.expandP=Math.max(0,portal.expandP-.05*k);portal.opacity=Math.min(1,portal.opacity+.06*k)}else if(portal.state==="IMMERSIVE"){portal.expandP=Math.min(1,portal.expandP+.035*k);portal.opacity=1}else if(portal.state==="CLOSING"){portal.closeP=Math.min(1,portal.closeP+.06*k);portal.opacity=1-ease(portal.closeP);if(portal.closeP>=1)resetPortal()}}
function resetPortal(){portal={state:"IDLE",cx:.5,cy:.5,w:.08,h:.08,angle:0,opacity:0,openP:0,expandP:0,closeP:0,lastSeen:0,openHold:0,closeHold:0};trail=[];manualPortal=false;badOpenFrames=0;updatePortalUI()}
function updatePortalUI(){$("portalState").textContent=portal.state;$("portalDebug").textContent=`${portal.state} · ${smoothRatio.toFixed(2)}×`;$("gesturePill").textContent=portal.state==="IDLE"?"SEPARATE BOTH HANDS":portal.state;$("gesturePill").classList.toggle("active",portal.state!=="IDLE")}
function sourceDims(){if(contentKind==="image")return{w:contentImage.naturalWidth||1,h:contentImage.naturalHeight||1};return{w:contentVideo.videoWidth||1,h:contentVideo.videoHeight||1}}
function drawLocalFitted(src,w,h){const d=sourceDims();let dx=-w/2,dy=-h/2,dw=w,dh=h;if(settings.fit!=="stretch"){const k=settings.fit==="contain"?Math.min(w/d.w,h/d.h):Math.max(w/d.w,h/d.h);dw=d.w*k;dh=d.h*k;dx=-dw/2;dy=-dh/2}ctx.drawImage(src,dx,dy,dw,dh)}
function portalGeometry(){const e=ease(portal.expandP),openScale=.12+.88*ease(portal.openP),cx=lerp(portal.cx*canvas.width,canvas.width/2,e),cy=lerp(portal.cy*canvas.height,canvas.height/2,e),w=lerp(portal.w*canvas.width,canvas.width*1.12,e)*openScale,h=lerp(portal.h*canvas.height,canvas.height*1.12,e)*openScale,angle=lerp(portal.angle,0,e);return{cx,cy,w,h,angle}}
function shapePath(w,h){ctx.beginPath();if(settings.look==="clean"){const r=Math.min(38,h*.12);ctx.moveTo(-w/2+r,-h/2);ctx.arcTo(w/2,-h/2,w/2,h/2,r);ctx.arcTo(w/2,h/2,-w/2,h/2,r);ctx.arcTo(-w/2,h/2,-w/2,-h/2,r);ctx.arcTo(-w/2,-h/2,w/2,-h/2,r);ctx.closePath()}else ctx.ellipse(0,0,w/2,h/2,0,0,Math.PI*2)}
function drawPortal(){if(portal.opacity<=.01)return;const g=portalGeometry();if(settings.trail&&portal.state!=="IMMERSIVE"){trail.unshift({...g});trail=trail.slice(0,3);trail.slice(1).forEach((q,i)=>drawEdge(q,.10/(i+1),true))}if(settings.dim>0){ctx.save();ctx.fillStyle=`rgba(0,0,0,${settings.dim*portal.opacity*(1-portal.expandP*.65)})`;ctx.fillRect(0,0,canvas.width,canvas.height);ctx.restore()}ctx.save();ctx.translate(g.cx,g.cy);ctx.rotate(g.angle);shapePath(g.w,g.h);ctx.clip();ctx.globalAlpha=settings.opacity;ctx.filter=`brightness(${settings.brightness}) contrast(${settings.contrast}) saturate(${settings.saturation})`;if(contentReady){const src=contentKind==="image"?contentImage:contentVideo;try{drawLocalFitted(src,g.w,g.h)}catch(e){out(`Draw failed: ${e.message}`)}}ctx.filter="none";ctx.globalAlpha=.16*(1-portal.expandP);const vignette=ctx.createRadialGradient(0,0,Math.min(g.w,g.h)*.15,0,0,Math.max(g.w,g.h)*.62);vignette.addColorStop(0,"rgba(0,0,0,0)");vignette.addColorStop(1,"rgba(0,0,0,.72)");ctx.fillStyle=vignette;ctx.fillRect(-g.w/2,-g.h/2,g.w,g.h);ctx.restore();drawEdge(g,portal.opacity,false)}
function drawEdge(g,a=1,ghost=false){ctx.save();ctx.translate(g.cx,g.cy);ctx.rotate(g.angle);ctx.globalAlpha=a;ctx.strokeStyle=settings.color;ctx.lineWidth=ghost?Math.max(1,settings.edge*.55):settings.edge;ctx.shadowColor=settings.color;ctx.shadowBlur=settings.glow*(ghost?.45:(.45+.55*settings.energy));shapePath(g.w,g.h);ctx.stroke();if(!ghost&&settings.look==="mystic"){const t=performance.now()*.001;ctx.lineWidth=Math.max(1,settings.edge*.32);for(let i=0;i<3;i++){ctx.globalAlpha=a*(.38+i*.12);ctx.setLineDash([18+i*7,14+i*5]);ctx.lineDashOffset=-(t*35*(i+1));shapePath(g.w+i*8,g.h+i*6);ctx.stroke()}ctx.setLineDash([]);if(settings.particles)drawParticles(g.w,g.h,t,a)}ctx.restore()}
function drawParticles(w,h,t,a){const n=Math.round(18+settings.energy*28);ctx.fillStyle=settings.color;for(let i=0;i<n;i++){const phase=i*2.399,a0=phase+t*(i%2?.42:-.31),rx=w/2+8*Math.sin(i*.73+t*1.7),ry=h/2+7*Math.cos(i*.91+t*1.3),x=Math.cos(a0)*rx,y=Math.sin(a0)*ry,r=1+(i%4)*.45;ctx.globalAlpha=a*(.18+.55*((i%9)/9));ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill()}}
function render(ts){raf=requestAnimationFrame(render);if(!inputReady||inputVideo.readyState<2){if(manualPortal){ctx.fillStyle="#090b09";ctx.fillRect(0,0,canvas.width,canvas.height);animatePortal(Math.min(50,ts-lastTs));drawPortal()}lastTs=ts;return}syncCanvas();drawInput();const dt=Math.min(50,Math.max(1,ts-lastTs));lastTs=ts;if(landmarker&&inputVideo.currentTime!==lastVideoTime){lastVideoTime=inputVideo.currentTime;try{const r=landmarker.detectForVideo(inputVideo,performance.now());updatePortal(handMetrics(r.landmarks,ts),dt,ts)}catch(e){status("TRACKER ERROR");out(e.message)}}else if(manualPortal)animatePortal(dt);drawPortal();const f=1000/dt;fps=fps?fps*.9+f*.1:f;$("metrics").textContent=`${fps.toFixed(0)} FPS · ${contentReady?"content ready":"no content"}`}
function loop(){if(!raf)raf=requestAnimationFrame(render)}
function diag(d={}){const hands=d.hands??0,intent=d.intent??0,ratio=d.ratio??smoothRatio,vel=d.velocity??0;$("diagHands").textContent=`${hands}/2`;$("diagIntent").textContent=intent.toFixed(2);$("diagRatio").textContent=`${ratio.toFixed(2)}×`;$("diagVelocity").textContent=(vel>=0?"+":"")+vel.toFixed(2);$("diagHold").textContent=`${Math.round(portal.openHold)}ms`;$("diagContent").textContent=contentReady?"READY":"EMPTY";$("diagState").textContent=hands>=2?"TRACKING":"WAITING";$("diagHands").className=hands>=2?"diag-good":"diag-bad";$("diagIntent").className=intent>=.5?"diag-good":"diag-warn";$("diagRatio").className=ratio>=settings.open?"diag-good":"diag-warn";$("diagContent").className=contentReady?"diag-good":"diag-bad"}
function save(){localStorage.setItem(KEY,JSON.stringify(settings));out("✓ Settings saved")}
function restore(){try{Object.assign(settings,JSON.parse(localStorage.getItem(KEY)||"{}"));syncUI();out("✓ Settings restored")}catch{}}
function labels(){$("opacityValue").textContent=(+settings.opacity).toFixed(2);$("brightnessValue").textContent=(+settings.brightness).toFixed(2);$("contrastValue").textContent=(+settings.contrast).toFixed(2);$("saturationValue").textContent=(+settings.saturation).toFixed(2);$("dimValue").textContent=(+settings.dim).toFixed(2);$("glowValue").textContent=settings.glow+"px";$("edgeValue").textContent=settings.edge+"px";$("energyValue").textContent=(+settings.energy).toFixed(2);$("smoothValue").textContent=(+settings.smoothing).toFixed(2);$("openValue").textContent=(+settings.open).toFixed(2)+"×";$("expandValue").textContent=(+settings.expand).toFixed(2)+"×";$("closeValue").textContent=(+settings.close).toFixed(2)+"×";$("lookState").textContent=settings.look.toUpperCase();diag()}
function syncUI(){$("mirrorInput").checked=settings.mirror;$("contentFit").value=settings.fit;$("contentOpacity").value=settings.opacity;$("brightness").value=settings.brightness;$("contrast").value=settings.contrast;$("saturation").value=settings.saturation;$("backdropDim").value=settings.dim;$("portalColor").value=settings.color;$("portalGlow").value=settings.glow;$("portalEdge").value=settings.edge;$("portalEnergy").value=settings.energy;$("particlesOn").checked=settings.particles;$("trailOn").checked=settings.trail;$("smoothing").value=settings.smoothing;$("openThreshold").value=settings.open;$("expandThreshold").value=settings.expand;$("closeThreshold").value=settings.close;$("intentGate").checked=settings.intent;document.querySelectorAll('[data-look]').forEach(b=>b.classList.toggle('active',b.dataset.look===settings.look));labels()}
function testPortal(){if(manualPortal){portal.state="CLOSING";manualPortal=false;return}manualPortal=true;portal.state="OPENING";portal.cx=.5;portal.cy=.5;portal.w=.48;portal.h=.28;portal.angle=0;portal.openP=0;portal.expandP=0;portal.closeP=0;portal.opacity=0;loop();status("TEST PORTAL ACTIVE");updatePortalUI()}
function record(){if(recorder&&recorder.state==="recording")return;try{const recFps=+$('recordFps').value,vs=canvas.captureStream(recFps),tracks=[...vs.getVideoTracks()];if($("micAudio").checked&&inputStream)tracks.push(...inputStream.getAudioTracks());if($("contentAudio").checked){if(contentStream)tracks.push(...contentStream.getAudioTracks());else if(typeof contentVideo.captureStream==="function"){try{tracks.push(...contentVideo.captureStream().getAudioTracks())}catch{}}}const stream=new MediaStream(tracks),mime=MediaRecorder.isTypeSupported("video/webm;codecs=vp9")?"video/webm;codecs=vp9":"video/webm";chunks=[];recorder=new MediaRecorder(stream,{mimeType:mime,videoBitsPerSecond:14_000_000});recorder.ondataavailable=e=>e.data.size&&chunks.push(e.data);recorder.onstop=()=>{const b=new Blob(chunks,{type:mime});download(b,`portal-studio-v211-${Date.now()}.webm`);$("recordingBadge").classList.remove("on");out(`✓ Video downloaded · ${(b.size/1024/1024).toFixed(1)} MB`)};recorder.start(250);$("recordingBadge").classList.add("on");out(`● Recording ${recFps} FPS`)}catch(e){out(`Recording error: ${e.message}`)}}
function download(blob,name){const a=document.createElement("a"),u=URL.createObjectURL(blob);a.href=u;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),2500)}
function wire(){$("startCamera").onclick=camera;$("gestureFile").onchange=e=>e.target.files[0]&&gestureFile(e.target.files[0]);$("mirrorInput").onchange=e=>settings.mirror=e.target.checked;$("testPortal").onclick=testPortal;document.querySelectorAll('[data-content]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-content]').forEach(x=>x.classList.toggle('active',x===b));const m=b.dataset.content;$("shareScreen").classList.toggle("hidden",m!=="screen");$("hlsBox").classList.toggle("hidden",m!=="hls");$("webrtcBox").classList.toggle("hidden",m!=="webrtc")});$("contentFile").onchange=e=>e.target.files[0]&&mediaFile(e.target.files[0]);$("shareScreen").onclick=share;$("loadHls").onclick=loadHls;$("clearRemote").onclick=()=>window.FingerFrameV211.clearRemoteStream();$("contentFit").onchange=e=>settings.fit=e.target.value;$("contentOpacity").oninput=e=>{settings.opacity=+e.target.value;labels()};$("brightness").oninput=e=>{settings.brightness=+e.target.value;labels()};$("contrast").oninput=e=>{settings.contrast=+e.target.value;labels()};$("saturation").oninput=e=>{settings.saturation=+e.target.value;labels()};$("backdropDim").oninput=e=>{settings.dim=+e.target.value;labels()};document.querySelectorAll('[data-look]').forEach(b=>b.onclick=()=>{settings.look=b.dataset.look;document.querySelectorAll('[data-look]').forEach(x=>x.classList.toggle('active',x===b));labels()});$("portalColor").oninput=e=>settings.color=e.target.value;$("portalGlow").oninput=e=>{settings.glow=+e.target.value;labels()};$("portalEdge").oninput=e=>{settings.edge=+e.target.value;labels()};$("portalEnergy").oninput=e=>{settings.energy=+e.target.value;labels()};$("particlesOn").onchange=e=>settings.particles=e.target.checked;$("trailOn").onchange=e=>settings.trail=e.target.checked;$("smoothing").oninput=e=>{settings.smoothing=+e.target.value;labels()};$("openThreshold").oninput=e=>{settings.open=+e.target.value;labels()};$("expandThreshold").oninput=e=>{settings.expand=+e.target.value;labels()};$("closeThreshold").oninput=e=>{settings.close=+e.target.value;labels()};$("intentGate").onchange=e=>settings.intent=e.target.checked;$("forceReset").onclick=resetPortal;$("previewClean").onclick=()=>document.body.classList.add("preview");$("exitPreview").onclick=()=>document.body.classList.remove("preview");document.addEventListener("keydown",e=>{if(e.key==="Escape")document.body.classList.remove("preview")});$("recordVideo").onclick=record;$("stopRecord").onclick=()=>recorder&&recorder.state==="recording"&&recorder.stop();$("downloadPng").onclick=()=>canvas.toBlob(b=>b&&download(b,`portal-studio-v211-${Date.now()}.png`));$("saveSettings").onclick=save;$("restoreSettings").onclick=restore}
wire();syncUI();updatePortalUI();status("V2.1.1 READY · HOTFIX");