import { HandLandmarker, FilesetResolver } from "https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.14";

const WASM_URL="https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.14/wasm";
const MODEL_URL="https://storage.googleapis.com/mediapipe-models/hand_landmarker/hand_landmarker/float16/1/hand_landmarker.task";
const $=id=>document.getElementById(id);
const canvas=$("canvas"),ctx=canvas.getContext("2d",{alpha:false}),inputVideo=$("inputVideo"),contentVideo=$("contentVideo"),contentImage=$("contentImage");
const STORAGE_KEY="finger-frame-studio-premium-v1";
let landmarker=null,inputMode="camera",contentMode="upload",inputStream=null,contentStream=null,contentKind=null,inputReady=false,contentReady=false;
let corners=null,presence=0,lastGood=null,lostFrames=0,lastDetectTime=-1,raf=0,lastFrameTs=performance.now(),fpsSmooth=0;
let recorder=null,chunks=[],preview=false;

const settings={mirror:true,fit:"cover",opacity:1,borderWidth:3,cornerSize:7,glow:14,color:"#f2cf64",outline:true,corners:true};

function setTop(text,type="ok"){$("topStatus").innerHTML=`<i></i>${text}`;$('topStatus').dataset.type=type}
function asset(el,text,ok=false){el.textContent=text;el.classList.toggle("ok",ok)}
function output(msg){$("outputMsg").textContent=msg;$("outputState").textContent=msg?"UPDATED":"READY"}
function fmtBytes(n){const u=["B","KB","MB","GB"];let i=0,v=n;while(v>=1024&&i<u.length-1){v/=1024;i++}return `${v.toFixed(i?1:0)} ${u[i]}`}

async function ensureLandmarker(){if(landmarker)return;setTop("LOADING HAND TRACKER");const fileset=await FilesetResolver.forVisionTasks(WASM_URL);landmarker=await HandLandmarker.createFromOptions(fileset,{baseOptions:{modelAssetPath:MODEL_URL,delegate:"GPU"},runningMode:"VIDEO",numHands:2,minHandDetectionConfidence:.35,minHandPresenceConfidence:.35,minTrackingConfidence:.35});setTop("HAND TRACKER READY")}

function stopInput(){if(inputStream){inputStream.getTracks().forEach(t=>t.stop());inputStream=null}inputVideo.pause();inputVideo.removeAttribute("src");inputVideo.srcObject=null;inputVideo.load();inputReady=false}
async function startCamera(){stopInput();try{await ensureLandmarker();inputStream=await navigator.mediaDevices.getUserMedia({video:{width:{ideal:1280},height:{ideal:720},frameRate:{ideal:30}},audio:true});inputVideo.srcObject=inputStream;inputVideo.muted=true;inputVideo.playsInline=true;await inputVideo.play();await waitMeta(inputVideo);inputReady=true;inputMode="camera";syncCanvas();$("inputState").textContent="LIVE";asset($("gestureAsset"),`Camera ${inputVideo.videoWidth}×${inputVideo.videoHeight}`,true);setTop("CAMERA LIVE");startLoop()}catch(e){setTop("CAMERA BLOCKED","error");output("Camera permission was not granted.")}}
function waitMeta(v){return v.readyState>=1?Promise.resolve():new Promise(r=>v.addEventListener("loadedmetadata",r,{once:true}))}

async function loadGestureVideo(file){stopInput();await ensureLandmarker();inputVideo.src=URL.createObjectURL(file);inputVideo.loop=$("loopInput").checked;inputVideo.muted=true;await waitMeta(inputVideo);inputReady=true;inputMode="upload";syncCanvas();$("inputState").textContent="VIDEO";asset($("gestureAsset"),`✓ ${file.name} · ${inputVideo.videoWidth}×${inputVideo.videoHeight} · ${inputVideo.duration.toFixed(1)}s · ${fmtBytes(file.size)}`,true);setTop("GESTURE VIDEO LOADED");await inputVideo.play().catch(()=>{});startLoop()}
function syncCanvas(){const w=inputVideo.videoWidth||1280,h=inputVideo.videoHeight||720;if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h}}

function stopContentStream(){if(contentStream){contentStream.getTracks().forEach(t=>t.stop());contentStream=null}}
function setContentVideo(src,label){stopContentStream();contentImage.removeAttribute("src");contentVideo.srcObject=null;contentVideo.src=src;contentVideo.loop=$("contentLoop").checked;contentVideo.muted=$("contentMute").checked;contentVideo.playsInline=true;contentKind="video";contentReady=true;contentVideo.play().catch(()=>{});asset($("contentAsset"),label,true);$("contentState").textContent="VIDEO"}
function setContentImage(src,label){stopContentStream();contentVideo.pause();contentVideo.removeAttribute("src");contentVideo.srcObject=null;contentImage.src=src;contentKind="image";contentReady=true;asset($("contentAsset"),label,true);$("contentState").textContent="IMAGE"}
async function loadContentFile(file){if(file.type.startsWith("video/")){setContentVideo(URL.createObjectURL(file),`✓ VIDEO · ${file.name} · ${fmtBytes(file.size)}`)}else if(file.type.startsWith("image/")){setContentImage(URL.createObjectURL(file),`✓ IMAGE · ${file.name} · ${fmtBytes(file.size)}`)}}
async function shareScreen(){try{stopContentStream();contentStream=await navigator.mediaDevices.getDisplayMedia({video:true,audio:true});contentVideo.srcObject=contentStream;contentVideo.muted=$("contentMute").checked;contentVideo.playsInline=true;await contentVideo.play();contentKind="video";contentReady=true;asset($("contentAsset"),"✓ SCREEN SHARE LIVE",true);$("contentState").textContent="SCREEN";contentStream.getVideoTracks()[0]?.addEventListener("ended",()=>{contentReady=false;$("contentState").textContent="EMPTY";asset($("contentAsset"),"Screen share ended.")})}catch{output("Screen share cancelled.")}}
function loadUrl(){const url=$("contentUrl").value.trim();if(!url)return;const lower=url.toLowerCase();if(/\.(png|jpg|jpeg|webp|gif)(\?|$)/.test(lower)){contentImage.crossOrigin="anonymous";setContentImage(url,"✓ IMAGE URL") }else{contentVideo.crossOrigin="anonymous";setContentVideo(url,"✓ VIDEO URL · CORS required for export")}}

function rawCorners(landmarks){if(!landmarks||landmarks.length<2)return null;const pts=[];for(const hand of landmarks.slice(0,2)){if(!hand[8]||!hand[4])continue;pts.push({x:hand[8].x*canvas.width,y:hand[8].y*canvas.height});pts.push({x:hand[4].x*canvas.width,y:hand[4].y*canvas.height})}if(pts.length!==4)return null;if(settings.mirror)pts.forEach(p=>p.x=canvas.width-p.x);const cx=pts.reduce((s,p)=>s+p.x,0)/4,cy=pts.reduce((s,p)=>s+p.y,0)/4;pts.sort((a,b)=>Math.atan2(a.y-cy,a.x-cx)-Math.atan2(b.y-cy,b.x-cx));let start=0,best=Infinity;pts.forEach((p,i)=>{const score=p.x+p.y;if(score<best){best=score;start=i}});const ordered=[0,1,2,3].map(i=>pts[(start+i)%4]);if(polygonArea(ordered)<canvas.width*canvas.height*.008)return null;return ordered}
function polygonArea(p){let a=0;for(let i=0;i<p.length;i++){const j=(i+1)%p.length;a+=p[i].x*p[j].y-p[j].x*p[i].y}return Math.abs(a)/2}
function smooth(next){if(!next)return null;if(!corners)return next.map(p=>({...p}));const alpha=.28;return next.map((p,i)=>({x:corners[i].x+(p.x-corners[i].x)*alpha,y:corners[i].y+(p.y-corners[i].y)*alpha}))}
function updateTracking(results){const next=rawCorners(results?.landmarks||[]);if(next){corners=smooth(next);lastGood=corners.map(p=>({...p}));lostFrames=0;presence=Math.min(1,presence+.16)}else{lostFrames++;if(lostFrames<16&&lastGood){corners=lastGood.map(p=>({...p}));presence=Math.max(0,presence-.035)}else{presence=Math.max(0,presence-.11);if(presence<.03)corners=null}}const active=!!corners&&presence>.15;$("gesturePill").textContent=active?"FINGER FRAME ACTIVE":"SHOW BOTH HANDS";$("gesturePill").classList.toggle("active",active);$("frameState").textContent=active?"TRACKING":"WAITING"}

function drawInput(){ctx.save();if(settings.mirror){ctx.translate(canvas.width,0);ctx.scale(-1,1)}ctx.drawImage(inputVideo,0,0,canvas.width,canvas.height);ctx.restore()}
function contentDimensions(){if(contentKind==="image")return {w:contentImage.naturalWidth||1,h:contentImage.naturalHeight||1};return {w:contentVideo.videoWidth||1,h:contentVideo.videoHeight||1}}
function drawFitted(source){const {w:sw,h:sh}=contentDimensions(),cw=canvas.width,ch=canvas.height;let dx=0,dy=0,dw=cw,dh=ch;if(settings.fit!=="stretch"){const scale=settings.fit==="contain"?Math.min(cw/sw,ch/sh):Math.max(cw/sw,ch/sh);dw=sw*scale;dh=sh*scale;dx=(cw-dw)/2;dy=(ch-dh)/2}ctx.drawImage(source,dx,dy,dw,dh)}
function drawFrame(){if(!corners||presence<=.01)return;const a=presence*settings.opacity;ctx.save();ctx.beginPath();ctx.moveTo(corners[0].x,corners[0].y);for(let i=1;i<corners.length;i++)ctx.lineTo(corners[i].x,corners[i].y);ctx.closePath();ctx.clip();ctx.globalAlpha=a;if(contentReady){const src=contentKind==="image"?contentImage:contentVideo;try{drawFitted(src)}catch{}}else{const g=ctx.createLinearGradient(0,0,canvas.width,canvas.height);g.addColorStop(0,"#15251c");g.addColorStop(.5,"#bca14c");g.addColorStop(1,"#201326");ctx.fillStyle=g;ctx.fillRect(0,0,canvas.width,canvas.height)}ctx.restore();
 if(settings.outline&&settings.borderWidth>0){ctx.save();ctx.beginPath();ctx.moveTo(corners[0].x,corners[0].y);for(let i=1;i<4;i++)ctx.lineTo(corners[i].x,corners[i].y);ctx.closePath();ctx.globalAlpha=presence;ctx.strokeStyle=settings.color;ctx.lineWidth=settings.borderWidth;ctx.setLineDash([12,9]);ctx.lineDashOffset=-(performance.now()/35)%21;ctx.shadowColor=settings.color;ctx.shadowBlur=settings.glow;ctx.stroke();ctx.restore()}
 if(settings.corners&&settings.cornerSize>0){ctx.save();ctx.fillStyle=settings.color;ctx.globalAlpha=presence;ctx.shadowColor=settings.color;ctx.shadowBlur=settings.glow;for(const p of corners){ctx.beginPath();ctx.arc(p.x,p.y,settings.cornerSize,0,Math.PI*2);ctx.fill()}ctx.restore()}}

function render(ts){raf=requestAnimationFrame(render);if(!inputReady||inputVideo.readyState<2)return;syncCanvas();drawInput();if(landmarker&&inputVideo.currentTime!==lastDetectTime){lastDetectTime=inputVideo.currentTime;try{updateTracking(landmarker.detectForVideo(inputVideo,performance.now()))}catch{}}drawFrame();const dt=Math.max(1,ts-lastFrameTs);lastFrameTs=ts;const instant=1000/dt;fpsSmooth=fpsSmooth?fpsSmooth*.9+instant*.1:instant;$("metrics").textContent=`${fpsSmooth.toFixed(0)} FPS · ${corners&&presence>.15?"frame active":"no frame"}`}
function startLoop(){if(!raf)raf=requestAnimationFrame(render)}

function collect(){return {...settings,loopInput:$("loopInput").checked,contentLoop:$("contentLoop").checked,contentMute:$("contentMute").checked}}
function applySaved(s){if(!s)return;Object.assign(settings,s);$("mirrorInput").checked=!!settings.mirror;$("contentFit").value=settings.fit;$("contentOpacity").value=settings.opacity;$("borderWidth").value=settings.borderWidth;$("cornerSize").value=settings.cornerSize;$("frameGlow").value=settings.glow;$("frameColor").value=settings.color;$("showOutline").checked=!!settings.outline;$("showCorners").checked=!!settings.corners;$("loopInput").checked=s.loopInput??true;$("contentLoop").checked=s.contentLoop??true;$("contentMute").checked=s.contentMute??true;syncLabels()}
function syncLabels(){$("fitValue").textContent=settings.fit.toUpperCase();$("opacityValue").textContent=(+settings.opacity).toFixed(2);$("borderValue").textContent=settings.borderWidth+"px";$("cornerValue").textContent=settings.cornerSize+"px";$("glowValue").textContent=settings.glow+"px"}

function startRecord(){if(recorder&&recorder.state==="recording")return;try{const fps=+$('recordFps').value;const videoStream=canvas.captureStream(fps);const tracks=[...videoStream.getVideoTracks()];if(inputMode==="upload"&&typeof inputVideo.captureStream==="function"){try{const s=inputVideo.captureStream();tracks.push(...s.getAudioTracks())}catch{}}else if(inputStream){tracks.push(...inputStream.getAudioTracks())}const stream=new MediaStream(tracks);const mime=MediaRecorder.isTypeSupported("video/webm;codecs=vp9")?"video/webm;codecs=vp9":"video/webm";chunks=[];recorder=new MediaRecorder(stream,{mimeType:mime,videoBitsPerSecond:12_000_000});recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};recorder.onstop=()=>{const blob=new Blob(chunks,{type:mime});download(blob,`finger-frame-${Date.now()}.webm`);$("recordingBadge").classList.remove("on");output(`✓ Video downloaded · ${(blob.size/1024/1024).toFixed(1)} MB`);setTop("RECORDING SAVED")};recorder.start(250);$("recordingBadge").classList.add("on");output(`● Recording ${fps} FPS`);setTop("RECORDING") }catch(e){output("Recording unavailable in this browser.")}}
function stopRecord(){if(recorder&&recorder.state==="recording")recorder.stop()}
function download(blob,name){const a=document.createElement("a"),u=URL.createObjectURL(blob);a.href=u;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),2500)}
function png(){canvas.toBlob(b=>{if(b){download(b,`finger-frame-${Date.now()}.png`);output("✓ PNG downloaded")}},"image/png")}
function setPreview(on){preview=on;document.body.classList.toggle("preview",on)}

function wire(){
 document.querySelectorAll("[data-input-mode]").forEach(b=>b.onclick=()=>{document.querySelectorAll("[data-input-mode]").forEach(x=>x.classList.toggle("active",x===b));inputMode=b.dataset.inputMode;if(inputMode==="camera")startCamera()});
 $("startCamera").onclick=startCamera;$("gestureFile").onchange=e=>e.target.files[0]&&loadGestureVideo(e.target.files[0]);$("mirrorInput").onchange=e=>settings.mirror=e.target.checked;$("loopInput").onchange=e=>inputVideo.loop=e.target.checked;$("inputPlay").onclick=()=>inputVideo.play();$("inputPause").onclick=()=>inputVideo.pause();$("inputRestart").onclick=()=>{inputVideo.currentTime=0;inputVideo.play()};
 document.querySelectorAll("[data-content-mode]").forEach(b=>b.onclick=()=>{document.querySelectorAll("[data-content-mode]").forEach(x=>x.classList.toggle("active",x===b));contentMode=b.dataset.contentMode;$("shareScreen").classList.toggle("hidden",contentMode!=="screen");$("urlBox").classList.toggle("hidden",contentMode!=="url")});
 $("contentFile").onchange=e=>e.target.files[0]&&loadContentFile(e.target.files[0]);$("shareScreen").onclick=shareScreen;$("loadUrl").onclick=loadUrl;$("contentFit").onchange=e=>{settings.fit=e.target.value;syncLabels()};$("contentOpacity").oninput=e=>{settings.opacity=+e.target.value;syncLabels()};$("contentLoop").onchange=e=>contentVideo.loop=e.target.checked;$("contentMute").onchange=e=>contentVideo.muted=e.target.checked;$("contentPlay").onclick=()=>contentVideo.play();$("contentPause").onclick=()=>contentVideo.pause();$("contentRestart").onclick=()=>{contentVideo.currentTime=0;contentVideo.play()};
 $("borderWidth").oninput=e=>{settings.borderWidth=+e.target.value;syncLabels()};$("cornerSize").oninput=e=>{settings.cornerSize=+e.target.value;syncLabels()};$("frameGlow").oninput=e=>{settings.glow=+e.target.value;syncLabels()};$("frameColor").oninput=e=>settings.color=e.target.value;$("showOutline").onchange=e=>settings.outline=e.target.checked;$("showCorners").onchange=e=>settings.corners=e.target.checked;
 $("previewClean").onclick=()=>setPreview(true);$("exitPreview").onclick=()=>setPreview(false);window.addEventListener("keydown",e=>{if(e.key==="Escape"&&preview)setPreview(false)});$("recordVideo").onclick=startRecord;$("stopRecord").onclick=stopRecord;$("downloadPng").onclick=png;$("saveSettings").onclick=()=>{localStorage.setItem(STORAGE_KEY,JSON.stringify(collect()));output("✓ Settings saved")};$("restoreSettings").onclick=()=>{try{applySaved(JSON.parse(localStorage.getItem(STORAGE_KEY)||"null"));output("✓ Settings restored")}catch{}};
 syncLabels();
}

wire();setTop("READY");startLoop();
