import {HandLandmarker,FilesetResolver} from "https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.14";
const WASM="https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.14/wasm";
const MODEL="https://storage.googleapis.com/mediapipe-models/hand_landmarker/hand_landmarker/float16/1/hand_landmarker.task";
const $=id=>document.getElementById(id),canvas=$("canvas"),ctx=canvas.getContext("2d",{alpha:false}),inputVideo=$("inputVideo"),contentVideo=$("contentVideo"),contentImage=$("contentImage");
const KEY="finger-frame-premium-v2";
let landmarker=null,inputStream=null,contentStream=null,hls=null,inputReady=false,inputMode="camera",contentKind=null,contentReady=false,raf=0,lastVideoTime=-1,lastFrame=performance.now(),fps=0,recorder=null,chunks=[];
let portal={state:"IDLE",cx:.5,cy:.5,w:.08,h:.08,angle:0,targetW:.08,targetH:.08,opacity:0,expanded:false,lastSeen:0,openHold:0,closeHold:0};
let classicCorners=null,classicPresence=0,lastClassic=null;
const settings={mirror:true,mode:"portal",look:"mystic",fit:"cover",opacity:1,color:"#f2b84b",glow:28,edge:5,energy:.7,particles:true,sensitivity:1,smoothing:.24,open:.18,expand:.62,close:.11};
function status(t){$("topStatus").textContent=t}function out(t){$("outputMsg").textContent=t;$("outputState").textContent=t?"UPDATED":"READY"}function asset(t,ok=false){$("contentAsset").textContent=t;$("contentAsset").style.color=ok?"#a9d7af":"#777"}
async function ensureTracker(){if(landmarker)return;status("LOADING TRACKER");const fs=await FilesetResolver.forVisionTasks(WASM);landmarker=await HandLandmarker.createFromOptions(fs,{baseOptions:{modelAssetPath:MODEL,delegate:"GPU"},runningMode:"VIDEO",numHands:2,minHandDetectionConfidence:.35,minHandPresenceConfidence:.35,minTrackingConfidence:.35});status("TRACKER READY")}
function stopInput(){if(inputStream){inputStream.getTracks().forEach(t=>t.stop());inputStream=null}inputVideo.pause();inputVideo.srcObject=null;inputVideo.removeAttribute("src");inputVideo.load();inputReady=false}
function waitMeta(v){return v.readyState>=1?Promise.resolve():new Promise(r=>v.addEventListener("loadedmetadata",r,{once:true}))}
async function camera(){stopInput();await ensureTracker();try{inputStream=await navigator.mediaDevices.getUserMedia({video:{width:{ideal:1280},height:{ideal:720},frameRate:{ideal:30}},audio:true});inputVideo.srcObject=inputStream;inputVideo.muted=true;await inputVideo.play();await waitMeta(inputVideo);inputReady=true;inputMode="camera";$("inputState").textContent="LIVE";$("gestureAsset").textContent=`Camera ${inputVideo.videoWidth}×${inputVideo.videoHeight}`;syncCanvas();loop()}catch{status("CAMERA BLOCKED")}}
async function gestureFile(f){stopInput();await ensureTracker();inputVideo.src=URL.createObjectURL(f);inputVideo.loop=true;inputVideo.muted=true;await waitMeta(inputVideo);inputReady=true;inputMode="upload";$("inputState").textContent="VIDEO";$("gestureAsset").textContent=`✓ ${f.name} · ${inputVideo.videoWidth}×${inputVideo.videoHeight}`;syncCanvas();await inputVideo.play().catch(()=>{});loop()}
function syncCanvas(){const w=inputVideo.videoWidth||1280,h=inputVideo.videoHeight||720;if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h}}
function stopContent(){if(contentStream){contentStream.getTracks().forEach(t=>t.stop());contentStream=null}if(hls){hls.destroy();hls=null}contentVideo.pause();contentVideo.srcObject=null;contentVideo.removeAttribute("src");contentVideo.load()}
function videoSource(src,label){stopContent();contentVideo.src=src;contentVideo.loop=true;contentVideo.muted=true;contentVideo.playsInline=true;contentKind="video";contentReady=true;contentVideo.play().catch(()=>{});asset(label,true);$("contentState").textContent="VIDEO"}
function imageSource(src,label){stopContent();contentImage.src=src;contentKind="image";contentReady=true;asset(label,true);$("contentState").textContent="IMAGE"}
function mediaFile(f){if(f.type.startsWith("video/"))videoSource(URL.createObjectURL(f),`✓ VIDEO · ${f.name}`);else if(f.type.startsWith("image/"))imageSource(URL.createObjectURL(f),`✓ IMAGE · ${f.name}`)}
async function share(){try{stopContent();contentStream=await navigator.mediaDevices.getDisplayMedia({video:true,audio:true});contentVideo.srcObject=contentStream;contentVideo.muted=true;contentKind="video";contentReady=true;await contentVideo.play();asset("✓ SCREEN SHARE LIVE",true);$("contentState").textContent="SCREEN"}catch{out("Screen share cancelled")}}
function loadHls(){const url=$("hlsUrl").value.trim();if(!url)return;stopContent();contentKind="video";contentReady=true;if(contentVideo.canPlayType("application/vnd.apple.mpegurl")){contentVideo.src=url}else if(window.Hls&&window.Hls.isSupported()){hls=new window.Hls({lowLatencyMode:true});hls.loadSource(url);hls.attachMedia(contentVideo)}else{return out("HLS is not supported in this browser")};contentVideo.muted=true;contentVideo.play().catch(()=>{});asset("✓ HLS STREAM LOADED",true);$("contentState").textContent="HLS"}
function setRemoteStream(stream){stopContent();contentStream=stream;contentVideo.srcObject=stream;contentKind="video";contentReady=true;contentVideo.muted=true;contentVideo.play().catch(()=>{});asset("✓ WEBRTC REMOTE STREAM",true);$("contentState").textContent="WEBRTC";return true}
window.FingerFrameV2={setRemoteStream,clearRemoteStream:()=>{stopContent();contentReady=false;contentKind=null;asset("Remote stream cleared")}};
function drawInput(){ctx.save();if(settings.mirror){ctx.translate(canvas.width,0);ctx.scale(-1,1)}ctx.drawImage(inputVideo,0,0,canvas.width,canvas.height);ctx.restore()}
function handData(hands){if(!hands||hands.length<2)return null;const centers=hands.slice(0,2).map(h=>({x:h[9].x,y:h[9].y}));if(settings.mirror)centers.forEach(p=>p.x=1-p.x);centers.sort((a,b)=>a.x-b.x);const a=centers[0],b=centers[1],dx=b.x-a.x,dy=b.y-a.y,dist=Math.hypot(dx,dy),cx=(a.x+b.x)/2,cy=(a.y+b.y)/2,angle=Math.atan2(dy,dx);return{a,b,dist,cx,cy,angle,hands}}
function updatePortal(data,dt){const now=performance.now();if(!data){if(now-portal.lastSeen>450){portal.opacity=Math.max(0,portal.opacity-.055);if(portal.opacity<.02){portal.state="IDLE";portal.expanded=false}}return}portal.lastSeen=now;const sens=settings.sensitivity,open=settings.open/sens,close=settings.close/sens,expand=settings.expand/sens;const s=settings.smoothing;
 if(portal.state==="IDLE"){if(data.dist>open){portal.openHold+=dt;if(portal.openHold>180){portal.state="OPENING";portal.cx=data.cx;portal.cy=data.cy;portal.opacity=.05}}else portal.openHold=0}
 if(portal.state==="OPENING"){portal.opacity=Math.min(1,portal.opacity+.08);if(portal.opacity>.92)portal.state="OPEN"}
 if(["OPEN","MANIPULATING","EXPANDED"].includes(portal.state)||portal.state==="OPENING"){portal.cx+=(data.cx-portal.cx)*s;portal.cy+=(data.cy-portal.cy)*s;portal.angle=lerpAngle(portal.angle,data.angle,s);portal.targetW=Math.min(.95,Math.max(.12,data.dist*1.22));portal.targetH=Math.min(.75,portal.targetW*.58);portal.w+=(portal.targetW-portal.w)*s;portal.h+=(portal.targetH-portal.h)*s;portal.state=portal.expanded?"EXPANDED":"MANIPULATING";
   if(data.dist>expand){portal.expanded=true;portal.state="EXPANDED"}else if(portal.expanded&&data.dist<expand*.78){portal.expanded=false;portal.state="MANIPULATING"}
   if(data.dist<close){portal.closeHold+=dt;if(portal.closeHold>220)portal.state="CLOSING"}else portal.closeHold=0}
 if(portal.state==="CLOSING"){portal.opacity=Math.max(0,portal.opacity-.09);portal.w*=.94;portal.h*=.94;if(portal.opacity<.03){portal.state="IDLE";portal.expanded=false;portal.openHold=portal.closeHold=0;portal.w=portal.h=.08}}
 $("portalState").textContent=portal.state;$("gesturePill").textContent=portal.state==="IDLE"?"SEPARATE BOTH HANDS":"PORTAL "+portal.state;$("gesturePill").classList.toggle("active",portal.state!=="IDLE")}
function lerpAngle(a,b,t){let d=((b-a+Math.PI*3)%(Math.PI*2))-Math.PI;return a+d*t}
function classicData(hands){if(!hands||hands.length<2)return null;let pts=[];for(const h of hands.slice(0,2)){pts.push({x:h[8].x,y:h[8].y},{x:h[4].x,y:h[4].y})}if(settings.mirror)pts.forEach(p=>p.x=1-p.x);const cx=pts.reduce((s,p)=>s+p.x,0)/4,cy=pts.reduce((s,p)=>s+p.y,0)/4;pts.sort((a,b)=>Math.atan2(a.y-cy,a.x-cx)-Math.atan2(b.y-cy,b.x-cx));return pts}
function updateClassic(hands){const n=classicData(hands);if(n){classicCorners=n.map((p,i)=>lastClassic?{x:lastClassic[i].x+(p.x-lastClassic[i].x)*settings.smoothing,y:lastClassic[i].y+(p.y-lastClassic[i].y)*settings.smoothing}:p);lastClassic=classicCorners.map(p=>({...p}));classicPresence=Math.min(1,classicPresence+.14)}else classicPresence=Math.max(0,classicPresence-.08);$("portalState").textContent=classicPresence>.15?"CLASSIC TRACKING":"CLASSIC WAITING"}
function sourceDims(){if(contentKind==="image")return{w:contentImage.naturalWidth||1,h:contentImage.naturalHeight||1};return{w:contentVideo.videoWidth||1,h:contentVideo.videoHeight||1}}
function drawFitted(src,x,y,w,h){const d=sourceDims();let dx=x,dy=y,dw=w,dh=h;if(settings.fit!=="stretch"){const k=settings.fit==="contain"?Math.min(w/d.w,h/d.h):Math.max(w/d.w,h/d.h);dw=d.w*k;dh=d.h*k;dx=x+(w-dw)/2;dy=y+(h-dh)/2}ctx.drawImage(src,dx,dy,dw,dh)}
function drawContentRect(x,y,w,h){if(!contentReady)return;const src=contentKind==="image"?contentImage:contentVideo;ctx.globalAlpha=settings.opacity*portal.opacity;try{drawFitted(src,x,y,w,h)}catch{}}
function drawPortal(){if(portal.opacity<=.01)return;ctx.save();const cx=portal.expanded?canvas.width/2:portal.cx*canvas.width,cy=portal.expanded?canvas.height/2:portal.cy*canvas.height,w=portal.expanded?canvas.width*1.08:portal.w*canvas.width,h=portal.expanded?canvas.height*1.08:portal.h*canvas.height,ang=portal.expanded?0:portal.angle;ctx.translate(cx,cy);ctx.rotate(ang);ctx.beginPath();if(settings.look==="clean")roundRect(ctx,-w/2,-h/2,w,h,Math.min(36,h*.12));else ctx.ellipse(0,0,w/2,h/2,0,0,Math.PI*2);ctx.clip();ctx.save();ctx.translate(-cx,-cy);drawContentRect(cx-w/2,cy-h/2,w,h);ctx.restore();ctx.restore();drawPortalEdge(cx,cy,w,h,ang)}
function roundRect(c,x,y,w,h,r){c.moveTo(x+r,y);c.arcTo(x+w,y,x+w,y+h,r);c.arcTo(x+w,y+h,x,y+h,r);c.arcTo(x,y+h,x,y,r);c.arcTo(x,y,x+w,y,r);c.closePath()}
function drawPortalEdge(cx,cy,w,h,ang){ctx.save();ctx.translate(cx,cy);ctx.rotate(ang);ctx.globalAlpha=portal.opacity;ctx.strokeStyle=settings.color;ctx.lineWidth=settings.edge;ctx.shadowColor=settings.color;ctx.shadowBlur=settings.glow*(.35+.65*settings.energy);ctx.beginPath();if(settings.look==="clean")roundRect(ctx,-w/2,-h/2,w,h,Math.min(36,h*.12));else ctx.ellipse(0,0,w/2,h/2,0,0,Math.PI*2);ctx.stroke();if(settings.look==="mystic"){ctx.lineWidth=Math.max(1,settings.edge*.35);ctx.globalAlpha=portal.opacity*.65;for(let i=0;i<3;i++){ctx.beginPath();ctx.ellipse(0,0,w/2+i*5,h/2+i*4,0,Math.random()*6.28,Math.random()*6.28+3.5);ctx.stroke()}if(settings.particles)particles(w,h)}ctx.restore()}
function particles(w,h){const n=Math.round(18+settings.energy*34),t=performance.now()*.001;ctx.fillStyle=settings.color;for(let i=0;i<n;i++){const a=(i/n)*Math.PI*2+t*(i%3?0.13:-0.09),rx=w/2+(Math.sin(i*9.17+t*2)*10),ry=h/2+(Math.cos(i*5.43+t*1.7)*8),x=Math.cos(a)*rx,y=Math.sin(a)*ry,r=1+(i%4)*.45;ctx.globalAlpha=portal.opacity*(.15+.65*((i%7)/7));ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill()}}
function drawClassic(){if(!classicCorners||classicPresence<.02)return;const p=classicCorners.map(q=>({x:q.x*canvas.width,y:q.y*canvas.height}));ctx.save();ctx.beginPath();ctx.moveTo(p[0].x,p[0].y);for(let i=1;i<4;i++)ctx.lineTo(p[i].x,p[i].y);ctx.closePath();ctx.clip();ctx.globalAlpha=classicPresence*settings.opacity;if(contentReady){const src=contentKind==="image"?contentImage:contentVideo;try{drawFitted(src,0,0,canvas.width,canvas.height)}catch{}}ctx.restore();ctx.save();ctx.strokeStyle=settings.color;ctx.lineWidth=settings.edge;ctx.shadowColor=settings.color;ctx.shadowBlur=settings.glow;ctx.globalAlpha=classicPresence;ctx.beginPath();ctx.moveTo(p[0].x,p[0].y);for(let i=1;i<4;i++)ctx.lineTo(p[i].x,p[i].y);ctx.closePath();ctx.stroke();ctx.restore()}
function render(ts){raf=requestAnimationFrame(render);if(!inputReady||inputVideo.readyState<2)return;syncCanvas();drawInput();const dt=Math.min(50,ts-lastFrame);lastFrame=ts;if(landmarker&&inputVideo.currentTime!==lastVideoTime){lastVideoTime=inputVideo.currentTime;try{const r=landmarker.detectForVideo(inputVideo,performance.now());if(settings.mode==="portal")updatePortal(handData(r.landmarks),dt);else updateClassic(r.landmarks)}catch{}}if(settings.mode==="portal")drawPortal();else drawClassic();const f=1000/Math.max(1,dt);fps=fps?fps*.9+f*.1:f;$("metrics").textContent=`${fps.toFixed(0)} FPS · ${settings.mode} · ${contentReady?"content live":"no content"}`}
function loop(){if(!raf)raf=requestAnimationFrame(render)}
function resetPortal(){portal={state:"IDLE",cx:.5,cy:.5,w:.08,h:.08,angle:0,targetW:.08,targetH:.08,opacity:0,expanded:false,lastSeen:0,openHold:0,closeHold:0};classicCorners=null;classicPresence=0;lastClassic=null}
function save(){localStorage.setItem(KEY,JSON.stringify(settings));out("✓ Settings saved")}
function restore(){try{Object.assign(settings,JSON.parse(localStorage.getItem(KEY)||"{}"));syncUI();out("✓ Settings restored")}catch{}}
function syncUI(){$("mirrorInput").checked=settings.mirror;$("gestureMode").value=settings.mode;$("contentFit").value=settings.fit;$("contentOpacity").value=settings.opacity;$("portalColor").value=settings.color;$("portalGlow").value=settings.glow;$("portalEdge").value=settings.edge;$("portalEnergy").value=settings.energy;$("particlesOn").checked=settings.particles;$("sensitivity").value=settings.sensitivity;$("smoothing").value=settings.smoothing;$("openThreshold").value=Math.round(settings.open*100);$("expandThreshold").value=Math.round(settings.expand*100);$("closeThreshold").value=Math.round(settings.close*100);labels();document.querySelectorAll('[data-look]').forEach(b=>b.classList.toggle('active',b.dataset.look===settings.look))}
function labels(){$("opacityValue").textContent=(+settings.opacity).toFixed(2);$("glowValue").textContent=settings.glow+"px";$("edgeValue").textContent=settings.edge+"px";$("energyValue").textContent=(+settings.energy).toFixed(2);$("sensitivityValue").textContent=(+settings.sensitivity).toFixed(2);$("smoothValue").textContent=(+settings.smoothing).toFixed(2);$("openValue").textContent=Math.round(settings.open*100)+"%";$("expandValue").textContent=Math.round(settings.expand*100)+"%";$("closeValue").textContent=Math.round(settings.close*100)+"%";$("lookState").textContent=settings.look.toUpperCase();$("gestureModeState").textContent=settings.mode.toUpperCase()}
function record(){if(recorder&&recorder.state==="recording")return;const fps=+$('recordFps').value,vs=canvas.captureStream(fps),tracks=[...vs.getVideoTracks()];if(inputStream)tracks.push(...inputStream.getAudioTracks());const stream=new MediaStream(tracks),mime=MediaRecorder.isTypeSupported("video/webm;codecs=vp9")?"video/webm;codecs=vp9":"video/webm";chunks=[];recorder=new MediaRecorder(stream,{mimeType:mime,videoBitsPerSecond:12_000_000});recorder.ondataavailable=e=>e.data.size&&chunks.push(e.data);recorder.onstop=()=>{const b=new Blob(chunks,{type:mime});download(b,`portal-studio-${Date.now()}.webm`);$("recordingBadge").classList.remove("on");out("✓ Video downloaded")};recorder.start(250);$("recordingBadge").classList.add("on");out(`● Recording ${fps} FPS`)}
function download(blob,name){const a=document.createElement("a"),u=URL.createObjectURL(blob);a.href=u;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),2500)}
function wire(){document.querySelectorAll('[data-input]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-input]').forEach(x=>x.classList.toggle('active',x===b));inputMode=b.dataset.input;if(inputMode==='camera')camera()});$("startCamera").onclick=camera;$("gestureFile").onchange=e=>e.target.files[0]&&gestureFile(e.target.files[0]);$("mirrorInput").onchange=e=>settings.mirror=e.target.checked;$("gestureMode").onchange=e=>{settings.mode=e.target.value;resetPortal();labels()};
 document.querySelectorAll('[data-content]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-content]').forEach(x=>x.classList.toggle('active',x===b));const m=b.dataset.content;$("shareScreen").classList.toggle("hidden",m!=="screen");$("hlsBox").classList.toggle("hidden",m!=="hls");$("webrtcBox").classList.toggle("hidden",m!=="webrtc")});$("contentFile").onchange=e=>e.target.files[0]&&mediaFile(e.target.files[0]);$("shareScreen").onclick=share;$("loadHls").onclick=loadHls;$("clearRemote").onclick=()=>window.FingerFrameV2.clearRemoteStream();$("contentPlay").onclick=()=>contentVideo.play();$("contentPause").onclick=()=>contentVideo.pause();$("contentRestart").onclick=()=>{contentVideo.currentTime=0;contentVideo.play()};$("contentFit").onchange=e=>settings.fit=e.target.value;$("contentOpacity").oninput=e=>{settings.opacity=+e.target.value;labels()};
 document.querySelectorAll('[data-look]').forEach(b=>b.onclick=()=>{settings.look=b.dataset.look;document.querySelectorAll('[data-look]').forEach(x=>x.classList.toggle('active',x===b));labels()});$("portalColor").oninput=e=>settings.color=e.target.value;$("portalGlow").oninput=e=>{settings.glow=+e.target.value;labels()};$("portalEdge").oninput=e=>{settings.edge=+e.target.value;labels()};$("portalEnergy").oninput=e=>{settings.energy=+e.target.value;labels()};$("particlesOn").onchange=e=>settings.particles=e.target.checked;$("sensitivity").oninput=e=>{settings.sensitivity=+e.target.value;labels()};$("smoothing").oninput=e=>{settings.smoothing=+e.target.value;labels()};$("openThreshold").oninput=e=>{settings.open=+e.target.value/100;labels()};$("expandThreshold").oninput=e=>{settings.expand=+e.target.value/100;labels()};$("closeThreshold").oninput=e=>{settings.close=+e.target.value/100;labels()};$("forceReset").onclick=resetPortal;
 $("previewClean").onclick=()=>document.body.classList.add("preview");$("exitPreview").onclick=()=>document.body.classList.remove("preview");document.addEventListener("keydown",e=>{if(e.key==="Escape")document.body.classList.remove("preview")});$("recordVideo").onclick=record;$("stopRecord").onclick=()=>recorder&&recorder.state==="recording"&&recorder.stop();$("downloadPng").onclick=()=>canvas.toBlob(b=>b&&download(b,`portal-studio-${Date.now()}.png`));$("saveSettings").onclick=save;$("restoreSettings").onclick=restore}
wire();syncUI();status("V2 READY · PORTAL ENGINE");